default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tubuyaki_development

test:
  <<: *default
  database: tubuyaki_test

production:
  <<: *default
  database: tubuyaki_production
  username: tubuyaki
  password: <%= ENV['TUBUYAKI_DATABASE_PASSWORD'] %>
